### ISSUE TITLE
Starting Zotero with BBT, on Kubuntu 18.04.2 Citations keys get reassigned each time

### ISSUE THREAD

**Issue by vuvlab** [retorquere/zotero-better-bibtex#1201]
**Report ID:**

**Expected behavior:**
With up to date Zotero and BBT, on Kub 18.04.02, open Zotero and all 11,000 citations in my shared group library already have their bbt citation keys, as they should. 

*Actual behavior:**
On Kubuntu Linux 18.04.02 I open Zotero (5.066) with BBT (5.1.85), and it says starting key manager, BBT assigning citation keys, found 11,489 without citation key.

It does this every time, reassigning the citation keys at each start of zotero.
This is a large Zotero shared Group Library, I also access it from Zotero/BBT on Win10, and on Win10, the keys are there when it opens, so the don't re-assign the keys. 

So the citation keys aren't getting stored in the zotero library.  And they would then get Sync'd to Zotero shared storage, and be present on all the computer.  
we have 30 users and 20 of these people in my research group run Linux. 
 
I have exported the zotero libary to a bib file, as suggested for performance, but no effect.

**Comment by retorquere** [comment]
Can you restart with debugging enabled (from the help menu), let zotero restart, and then submit a bbt error report?

**Comment by retorquere** [comment]
> So the citation keys aren't getting stored in the zotero library. And they would then get Sync'd to Zotero shared storage, and be present on all the computer.
we have 30 users and 20 of these people in my research group run Linux.

The keys never get stored in the zotero library BTW; Zotero has a private database that is only local. Until Zotero adds the (already planned) citekey field, the only way to sync BBT keys htourgh zotero storage is to pin them.

That said, the local database should still retain the local keys, not regenerate them at every startup, so I'm going to look at that once I have the logs, but syncing without pinning is not part of this.

**Comment by vuvlab** [comment]
Okay, on my linux machine I enabled debugging, quit zotero, restarted it and let it finish finding and making 11000 keys. 
I like understanding how things work, and so hearing that the citekeys aren't stored, but are made localling is interesting.  
I attach the debugoutput.html file. 
And thanks for a great tool.  bbt is a great improvement.

[1906French-CWRU-DebugOutput.zip](https://github.com/retorquere/zotero-better-bibtex/files/3266113/1906French-CWRU-DebugOutput.zip)

**Comment by retorquere** [comment]
The BBT database is malformed, and it looks like the regular Zotero DB rollback isn't activated. Can you give me a listing of your Zotero data directory? There should be a file called better-bibtex.sqlite in that directory.

**Comment by vuvlab** [comment]
Here it is
![Screenshot_20190607_230410](https://user-images.githubusercontent.com/5075116/59109794-a9d68580-8978-11e9-90d9-df4da5a74269.png)

**Comment by retorquere** [comment]
Thanks. Can you do the same when Zotero is not running?

**Comment by retorquere** [comment]
Is this directory ran on a synced (eg dropbox) folder? Is Linux NTFS write support reliable these days?

**Comment by vuvlab** [comment]
![Screenshot_20190607_232502](https://user-images.githubusercontent.com/5075116/59111195-819c5600-897b-11e9-84e1-4ad800594f2c.png)
Here is the screenshot with Zotero closed.

This is not on a remote filesystem like dropbox. 

It is on a D: partition that is ntfs formatted, and this computer is dual boot.  
So periodically (say every 2 months ) I'll boot windows and let all those windows updates process through for a few days.
So this folder is used by both Linux Zotero/BBT and Windows Zotero/bbt.
This hasn't cause apparent problems with zotero alone (I do this on 10 computers configured like this).

And ntfs read/write is robust and reliable now adays.

**Comment by retorquere** [comment]
Can you close Zotero and get me a copy of your `better-bibtex.sqlite` (make sure you don't see a `sqlite-journal` file).

Your database is corrupted. I rely on sqlite (as does Zotero) to keep your DB sound, but storing it on dropbox will sooner or later corrupt your DB (which is why I was asking). I'm going to assume NTFS is OK here, but note that auto-exports if you have them set up don't work cross-platform as the paths are stored in the DB).

I will put out a build shortly that should detect the corruption and allow you to proceed, but if you get me the corrupt database I can test how it behaves before you try it.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4081](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4081.xpi) ("detect corrupt DB")

Install in Zotero by downloading [test build 5.1.85.4081](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4081.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by vuvlab** [comment]
here is the sqllite file, there was a journal file also, so I included that.

[zotero.zip](https://github.com/retorquere/zotero-better-bibtex/files/3268660/zotero.zip)

**Comment by vuvlab** [comment]
![Screenshot_20190609_000937](https://user-images.githubusercontent.com/5075116/59149016-01ddbc80-8a4b-11e9-87df-8c97b88c3321.png)
So now I installled the test build, and when I restarted it gave me the attached message. 
No I restart again, and its assinging citatino keys

**Comment by retorquere** [comment]
> here is the sqllite file, there was a journal file also, so I included that.

I don't need the journal file, but I must be absolutely certain that you copied the sqlite file while the journal file was **not** present. If the journal file is present, that means Zotero is running, you must not copy (or send, which is a copy) the `.sqlite` file while Zotero is running as it may be modifying it at the time. If you sent me this file while Zotero was running, please send a new copy while Zotero is not running, and the journal file is *not* present.

**Comment by retorquere** [comment]
I see the timestamps are exactly the same on `better-bibtex.sqlite` and `better-bibtex.sqlite-journal` in the zip file, which means they're likely taken at the same time when Zotero was running. Can you get me a file listing of your zotero dir again?

**Comment by retorquere** [comment]
> So now I installled the test build, and when I restarted it gave me the attached message.
> No I restart again, and its assinging citatino keys

I'd need to see a listing of the Zotero data dir to know what's going on, but if you didn't get this same popup again after the restart, it means it couldn't find any keys in the restored database. Let it finish, restart Zotero again, and then it should start without regenerating. If that is not the case:

1. Go to `Help` - `Debug Output Logging` - `Restart with logging enabled`
2. Once Zotero has started again, go to `Help` - `Report Better BibTeX Errors` and send post the resulting debug ID here.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4082](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4082.xpi) ("make popup a little more readable")

Install in Zotero by downloading [test build 5.1.85.4082](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4082.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by vuvlab** [comment]
![Screenshot_20190609_071233](https://user-images.githubusercontent.com/5075116/59152759-fcea2e80-8a85-11e9-8d44-654d5a0260f3.png)
This is the current zotero directory. I already installed the test build.  (I'm in Japan, so I think 12 hours off of you time).

**Comment by retorquere** [comment]
That's ok. Can you

1. Go to `Help` - `Debug Output Logging` - `Restart with logging enabled`
2. Once Zotero has started again, go to `Help` - `Report Better BibTeX Errors` and post the resulting debug ID here.

**Comment by vuvlab** [comment]
Here is the bbt debug id AHWDVMDL-apse

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4086](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4086.xpi) ("Zotero might already have moved the corrupted DB")

Install in Zotero by downloading [test build 5.1.85.4086](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4086.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Can you install 4086 and generate a new debug log with the same procedure?

**Comment by vuvlab** [comment]
Here is the debug log ID EDFKU9KY-apse,
From after installing 4086 test build

**Comment by retorquere** [comment]
Can you see if there's a file ending with `damaged` in your Zotero dir?

**Comment by vuvlab** [comment]
![Screenshot_20190609_165108](https://user-images.githubusercontent.com/5075116/59156462-d6a0af00-8ad6-11e9-9e89-9cda714010de.png)
directory listing, with Zotero closed.
No Damaged, but one called better-bibtex.sqlite.is.corrupt

**Comment by retorquere** [comment]
The `is.corrupt` is my doing, but your log says

```
3)(+0000124): {better-bibtex +692} FileStore.migrate: {"path":"/home/frenchrh/Data-ntfs/zotero/cache.sqlite","exists":false}
(3)(+0000002): {better-bibtex +2} FileStore.migrate: {"path":"/home/frenchrh/Data-ntfs/zotero/better-bibtex.sqlite","exists":false}
(3)(+0000000): [better-bibtex] Asynchronously opening database 'better-bibtex'
(3)(+0000000): /home/frenchrh/Data-ntfs/zotero/better-bibtex.sqlite
(1)(+0000044): Error: 2152857611

    Zotero.DBConnection.prototype._getConnectionAsync@chrome://zotero/content/xpcom/db.js:1150:13
(1)(+0000000): [better-bibtex] Database file 'better-bibtex.sqlite' corrupted
(1)(+0000002): [better-bibtex] Saving damaged DB file with .damaged extension
```

which means, if I interpret things correctly:

1. I determine that there's no file `/home/frenchrh/Data-ntfs/zotero/better-bibtex.sqlite`, so Zotero is expected to create a new DB
2. Zotero seems to create and open the DB but immediately reports it as damaged
3. Zotero claims it saves the damaged DB with the `.damaged` extension

I currently have no idea why Zotero is doing 2. and 3. I'm trying to diagnose the problem with the zotero devs [here](https://groups.google.com/forum/#!topic/zotero-dev/qTbzFUMup-E) but from what I can see, this simply should not happen.

Is this NTFS volume on a removable drive?

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4087](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4087.xpi) ("more logging around corruption handling")

Install in Zotero by downloading [test build 5.1.85.4087](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4087.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Ignore 4087

**Comment by vuvlab** [comment]
No its an ntfs volume, created by Windows, and then is a shared drive between Linux and Windows 10.
So the ntfs volume is d: drive in Windows. I create it by windows, after shrinking the size of C:. 
And the I leave a bunch of free space, where when I install Kubuntu18.04.2 (latest versino).
             I have linux make the ext4 partitions. 

and all of these are on the main SSD drive of the computer.

**Comment by blip-bloop** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.1.85.4088](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4088.xpi) ("Zotero DB restore is not quite as useful as I thought it would be")

Install in Zotero by downloading [test build 5.1.85.4088](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-5.1.85.4088.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
Give 4088 a go; I doubt the `restore` function will work (I hope the Zotero devs weigh in on the developers forum, if not, I'm removing it), but `reset` should now work.

**Comment by retorquere** [comment]
The database is repairable with a modification of the [zotero db fix](https://www.zotero.org/utils/dbfix/manual) instructions, but after repair the damaged DB has only a single autoexport set and no citekeys.

I have no idea what caused the corruption BTW. AFAIK, BBT should be incapable of corrupting the sqlite DB (that's what sqlite is supposed to quarantee), so the possible culprits I know are

* a sudden power loss (but even then sqlite is generally hardened against that)
* some kind of concurrent access (Zotero locks the database against concurrent use, but I don't know whether that's supported on NTFS)
* actual SSD corruption (which is possible but very rare)

**Comment by vuvlab** [comment]
Hi, Emiliano, So I think the issue probably is your 2nd point. 
         So I have used the same zotero folder on my dual boot machine (since its about 11Gb in size, we store pdf's with the citation information). So  I wanted to save that space.
          But concurrent, or may be even sequential access from two diffrernet OS's with different file pathying, courrupted. it.

            So in 4088, it said my db was corrupted, and so I choose reset. 
            And I'll now have a "good" database, and will just make one for zotero-lin and one for zotero-win10. 

          Let me see if that fixses it (Its still assigning citation keys now again after the reset)

**Comment by retorquere** [comment]
But in a dual boot situation you don't have concurrent access, and sequential shouldn't matter. The auto-export would only work on the os that it was set up with, but it should harmlessly fail on the other, and it certainly shouldn't be able to corrupt the db.

**Comment by vuvlab** [comment]
So I also have a VMWare VM, which is installed on my linux side, and which runs concurrently with linux. 
        And that one would mean I could have concurrent access to that folder, from linux and win10 VM. 
        Now you said that sqllite should block concurrent database access, but  that is how it could have happened. 
   
Still a problems arises, I think,  
       Running 4088 build, When I start Zotero, it tells me my database is corrupt (I believe I learned from you I have two dbs, one for Zotero and one for BBT).  
          If I choose the first option, (restart zotero and attempt restore), it restarts and tells me its corrupt again. 
           If I choose reset and start an new DB. It proceeds, reindexes everything. and all looks good.  
         But when I restart zotero, I sitll get the same "There was an error opening your database. 

Since I want to learn what is the right configuration, i.e. what to do and what to avoid doing. 
           So I make a Zotero folder on my linux home partiition (formatted as ext4 filesystem), This should avoid any ntfs problems, and make it so that I can't access it from dual boot windows). 
            I don't move any files into the empty zotero directory on home/frenchrh/Zotero.
            Just start sync'ing from my zotero group library.

So now if I quit zotero, and reopen it (even though it hasn't fullly sync'd), the cites present have their keys still defined. 
So this seems like a workable approach. 

Question should I just keep using test-build 4088?  
Or do a "check for updates" to get to the current BBT?  

Thanks for you help on this.

**Comment by retorquere** [comment]
> So I also have a VMWare VM, which is installed on my linux side, and which runs concurrently with linux. And that one would mean I could have concurrent access to that folder, from linux and win10 VM. Now you said that sqllite should block concurrent database access, but that is how it could have happened.

SQlite should, but you're making its job very hard in this case. Locking is done using OS primitives -- I'm not sure how that works with a VM involved, as VMs have very low-level OS access. For sure you do *not* want two Zotero's running simultaneously on the same data directory. If you try that on a single OS, Zotero will stop you using its file locking. Dual-access, however one gets there, is a fairly sure way to corrupt a Zotero DB.

BTW, since this kind of corruption is not something BBT *can* cause, there's something about your setup that does this damage. That means that your main Zotero DB with all your items is also at risk. BBT writes the database more often than Zotero does its own, this may be why the damage shows up there more easily, but in such a case, BBT is just the canary for more serious problems ahead.

> Still a problems arises, I think, Running 4088 build, When I start Zotero, it tells me my database is corrupt (I believe I learned from you I have two dbs, one for Zotero and one for BBT).

That is correct.

> If I choose the first option, (restart zotero and attempt restore), it restarts and tells me its corrupt again.

Yeah I figured that wouldn't work. I'm talking to the Zotero devs how the recovery mechanism is supposed to work but for now I'm just going to remove it.

> If I choose reset and start an new DB. It proceeds, reindexes everything. and all looks good. But when I restart zotero, I sitll get the same "There was an error opening your database.

I'll need a new debug log for this, again using

1. Go to `Help` - `Debug Output Logging` - `Restart with logging enabled`
2. Once Zotero has started again, go to `Help` - `Report Better BibTeX Errors` and send post the resulting debug ID here.

but I think it's likely it'll show the same problem as before: sees the DB is missing, create a new one, says *that* is corrupt, claims to copy it to `damaged` but doesn't.

> Since I want to learn what is the right configuration, i.e. what to do and what to avoid doing. So I make a Zotero folder on my linux home partiition (formatted as ext4 filesystem), This should avoid any ntfs problems, and make it so that I can't access it from dual boot windows).

Correct. I don't actually know whether the setup you have should or shouldn't work -- I'm still waiting for the Zotero devs to weigh in. I don't see any immediate reason why it *shouldn't* work, except for a situation where you have a Zotero running in the VM on the same datadir. If those both start up, that means Zotero locking doesn't work, and that they can simultaneously change the DB -- this should absolutely be avoided.

> I don't move any files into the empty zotero directory on home/frenchrh/Zotero. Just start sync'ing from my zotero group library.

That is possible. It's also possible to have the attachments shared but it's  substantially more difficult to set up and use.

> Question should I just keep using test-build 4088? Or do a "check for updates" to get to the current BBT?

I'm going to remove the "attempt restore" but keep the damage check, so I'll roll that into a new formal release. You'll be updated automatically to that in a day or so when Zotero checks for updates. Once the new release is out (somewhere today), a check updates will get you that upgrade immediately, but if you wait, you'll also get it. The only difference will be the removed "restore" option.

**Comment by vuvlab** [comment]
That sounds good.  
   I like it if you decide BBT can say " you have a corrupted database" since that alerts a problem, that is important, and I didn't understand existed before.
   So I'll check tomorrow for the new version, 
       And for my research group, I'll post an update with what rules to follow when setting up Zotero and BBT on dual-boot mahcines. 
       Which basically is put the Zotero directory on a native partition, and don't share the zotero directory between copies of Zotero running on different OS's. 

       I appreciate your work. And I teach 100 students a year datascience who all use LaTeX and Zotero.  
       So I think the future holds more open source and code based computer use. 
Thanks

**Comment by retorquere** [comment]
You're welcome.

Whether Zotero should be usable on a shared NTFS partition I really can't comment on -- I don't see any reason why it shouldn't work (even when used from a VM), but this you could ask on the general Zotero forums -- WRT database support, anything that goes for Zotero goes for BBT. I am absolutely sure though that concurrent use is out of the question. If it looks like it might work, that's actually the most dangerous situation. Same goes for Dropbox.

**Comment by retorquere** [comment]
The new version is out
