### ISSUE TITLE
Stuck in "Better BibTex: Initializing Loading citation keys"

### ISSUE THREAD

**Issue by NoxMortem** [retorquere/zotero-better-bibtex#2034]
Zotero Better Bibtex is permanently stuck in Better BibTex: Initializing Loading citation keys"
![grafik](https://user-images.githubusercontent.com/6750572/152125236-e41476b6-d164-42f3-9d6f-adfedab19877.png)

I am not able to export to a bib file anymore.

The settings pane constantly shows "Better BibTeX is loading"
![grafik](https://user-images.githubusercontent.com/6750572/152125517-49537a31-19a5-4163-b364-07e0cd6e60a8.png)

The error console is showing some errors:
![grafik](https://user-images.githubusercontent.com/6750572/152125703-c86cb057-5b34-43ac-aba6-136c2c63d10b.png)

Exporting never finishes
![grafik](https://user-images.githubusercontent.com/6750572/152125916-31d75059-f12c-4e3f-bb8e-bf4920b2b2d2.png)

Support log ID: W5UWWHKD-euc
Debug ID: D1463431258

After disabling, restarting, enabling, restarting again the "Better Biblatex" Format is not an export option anymore, but the warning still shows:
![grafik](https://user-images.githubusercontent.com/6750572/152128228-6c16b5d2-2c61-45ed-83f1-d3919eed0e49.png)

**Comment by retorquere** [comment]
Can you quit zotero and get me a copy of `better-bibtex.sqlite` and the JSON files in the `better-bibtex` directory?

**Comment by NoxMortem** [comment]
@retorquere here you are.
[Zotero.zip](https://github.com/retorquere/zotero-better-bibtex/files/7985403/Zotero.zip)

**Comment by retorquere** [comment]
2 things:

* there's an error in the log that seems to indicate BBT cannot write to `C:\Users\Kevin Streicher\Documents\repositories\visionary\Latex\Anmeldung\intro.bib`. This should be otherwise harmless
* In some way an extra field named `updated` made it into your auto-export database. I have no idea how it got there, I can't find any code that would put it there, but if you replace your `better-bibtex.sqlite` with the attached version I attached here, BBT should start up again.
[better-bibtex.sqlite.zip](https://github.com/retorquere/zotero-better-bibtex/files/7989941/better-bibtex.sqlite.zip)

**Comment by NoxMortem** [comment]
@retorquere 
`C:\Users\Kevin Streicher\Documents\repositories\visionary\Latex\Anmeldung\intro.bib`  does not exist, so the error is expected, but as the setting dialog does not load, I cannot change it either. 

I have replaced the file but there is no change.

![grafik](https://user-images.githubusercontent.com/6750572/152349173-2bee61e2-fb71-4b4d-bbe0-f0ec18208602.png)

However, I have removed the auto export entry and this fixed it
``` sql
delete from "better-bibtex"
where name = 'better-bibtex.autoexport';
```

Better Bibtex might need a check if a path is valid before endlessly hanging - which is in particular nasty, as it would have been nice to edit that from the settings dialog instead of the sqlite db.

**Comment by retorquere** [comment]
The path not existing was not the cause of the error; BBT caught and handled that and made a note of it, that's how I knew. I merely mentioned that as an FYI, it was not part of the problem diagnosis. BBT knows how to handle this situation. 

The problem was that something changed the structure of the BBT database, and BBT could not handle that unexpected change. I have no idea how the change got there, as I cannot find any code that could have made the change. By deleting the auto export you removed the misshapen record, and that fixed it. In the attachment I put here I fixed the record itself, retaining the auto export.

**Comment by NoxMortem** [comment]
@retorquere I **did** try your attached sqlite version and it did not work. I have used it and **then** deleted the entry. After that it worked. It is still reproducable.

If I compare the content of your version from the zip and the version that is the result after deleting the autoexport and letting it re-initialize I can see that more data changes:
![grafik](https://user-images.githubusercontent.com/6750572/152354214-c08242f3-fe92-4ba7-919d-2c1326dabada.png)
Left: better-bibtex,autoexport from your file (formatted)
Right: better-bibtex,autoexport after deleting it and letting Zotero/Better-bibtex reinitialize the field (formatted)
![grafik](https://user-images.githubusercontent.com/6750572/152354289-157a922f-4cd7-45a0-9a62-4b02950d08f8.png)
![grafik](https://user-images.githubusercontent.com/6750572/152354326-0a906442-2dc0-40c6-bc32-b64de54fe4a7.png)
![grafik](https://user-images.githubusercontent.com/6750572/152354351-7acd9468-ce19-43fd-8f00-be4225dc3a3d.png)

The same for better-bibtex.citekey
Left: from the zip file
Right: from the zip file, after deleting the key
![grafik](https://user-images.githubusercontent.com/6750572/152354758-3c1d6f80-6356-4cb7-8a0b-125e5a6bfb63.png)
![grafik](https://user-images.githubusercontent.com/6750572/152354925-8457747d-0779-4fa6-8704-bbed31ddc13e.png)

Shows that after deletion it was able to load the plugin and update the entry, as there have been pending additions in the Zotero bibliography that were not processed before.

If it helps I have just reproduced the problem with your file from the zip:
- Close Zotero
- Replace better-bibtex.sqlite
- Send Debug Report File
- Restart with activated logging
- Send Debug Report file
- Support ID: 8WF5IFKP-euc

**Comment by retorquere** [comment]
I should have tested the modified DB, that's on me, as there are more errors in that DB.

The diffs don't show anything special except cloneObjects being different, but the auto-export that was in the DB did not just have an extra field but it's also missing fields, while still being valid JSON. I have absolutely no idea how your DB could have gotten into this state, because the error you experience should have caused this record to be unsavable -- thereby preventing the error you now experience. TBH it looked like an unupgraded BBT database from at least a few years ago. Wait, that would explain all these differences in fact! Can that be the case?

So yeah, deleting that entry will solve it. I have added code in 2025 to detect errors of this kind which will auto-fix the database on next start. Can you give that a go? It works for me here.

**Comment by NoxMortem** [comment]
@retorquere sounds about right. I have not used Zotero since ~2017 i believe.

It did detect the error, however it then hangs in some different scenario:
![grafik](https://user-images.githubusercontent.com/6750572/152528803-067d4a70-258d-410a-ba70-de871336c534.png)
![grafik](https://user-images.githubusercontent.com/6750572/152528913-d0484d5b-147a-4636-807e-f1767c5cc891.png)
![grafik](https://user-images.githubusercontent.com/6750572/152528953-6ac0d3da-6e76-4cc0-91c7-fc6a691a3b06.png)
Restarting it then once more fixed it.
![grafik](https://user-images.githubusercontent.com/6750572/152529111-89f515f3-31c0-45f6-b9cf-14d3894c00f2.png)
 I guess that is "good enough", What would you say?

**Comment by retorquere** [comment]
Welcome back 🙂. 

If the current implementation satisfies you, it's good for me. Alternately, I could see if I could fix the auto-export rather then removing it.

**Comment by NoxMortem** [comment]
i am ;) I'd say it was good to make it self-repairing for non-tech savvy users. Also the affected user group likely is rather small if it was only because of the large jump in version.
