### ISSUE TITLE
[Bug]: plugin does not finish initialization

### ISSUE THREAD

**Issue by JackFishxxx** [retorquere/zotero-better-bibtex#2612]
### Debug log ID

D2121089932

### What happened?

My Zotero version: 6.0.26
BBT version: 6.7.102/103/104

The BBT always stucks at "BBT: TexStudio Support", and the used resources are 0% CPU and 300M Mem. I have tried to reinstall BBT but nothing changed.

The debug log stucks at "Writing column prefs of length 2177 to file C:\Users\xxx\AppData\Roaming\Zotero\Zotero\Profiles\xxx.default\treePrefs.json" at the beginning, I change the original file treePrefs.json to treePrefs_old.json, and the log goes to "itemTree.render(). Displaying Item Tree", but the BBT still stucks at "BBT: TexStudio Support".

Is there anything I can do to fix the BBT?

**Comment by JackFishxxx** [comment]
Sorry, but it seems that there is no "Send Better BibTeX debug report..." in my help menu, I only have "send debug log to file.io", I click it and it says :"debug log-id for BBT", is that correct?
the id is tYeyrZU06yj2-QXFGMP76

**Comment by retorquere** [comment]
That's what I meant, yes. Can you try whether https://github.com/retorquere/zotero-better-bibtex/issues/2610#issuecomment-1667041918 fixes the problem for you?

**Comment by JackFishxxx** [comment]
I am sorry for the delay, but nothing was changed after i installed [test build 6.7.104.2610.4856](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.104.2610.4856.xpi)

the log id is 
xR767DC0yuOK-BS7U2GSQ

**Comment by retorquere** [comment]
There's a file in your profile named `save-file\better-bibtex-search.sqlite` of which Zotero says it's not a database. Deleting that file should solve the problem, but could it be you tried to modify this file manually?

**Comment by JackFishxxx** [comment]
I have tried to edit the `better-bibtex-search.sqlite` file, but I dont have a sqlite editor on my computer currently, so I use a [SQLite online Editor](https://inloop.github.io/sqlite-viewer/) to try to edit the file. But the result says that `Error: file is not a database`, it seems that the database is broken, right?

I have changed the name of orginal file to `better-bibtex-search_old.sqlite`, and Zotero generates a new sqlite database. And the problem fixed, nothing is wrong now. 

Great thanks for you help! It really helps me!

**Comment by retorquere** [comment]
Please don't edit the sqlite file. Any idea how it got corrupted?

**Comment by JackFishxxx** [comment]
I have already backup the corrupted `better-bibtex-search.sqlite` to `better-bibtex-search_old.sqlite` and all my attempt on opening the corrupted file is failed.

I do not have any idea on how it got corrupted, but here is some information that may help you find the root of the problem:

1. I have tried the released version of 6.7.102/103/104 at the beginning, but the problem did not fix. After I installed [test build 6.7.104.2610.4856](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.104.2610.4856.xpi) and upload the debug log, you say that the sqlite file is corrupted. I delete this file after I backup it, and the problem fix.

2. Then I tried to edit the backup file, but failed. The result says that `Error: file is not a database`.

3. So, I backup all my BBT files in `save-file\`, including

> save-file\better-bibtex\ (some `json` file and `json.bak` file in it)
> save-file\better-bibtex.sqlite
> save-file\better-bibtex.sqlite.1.bak
> save-file\better-bibtex.sqlite.bak
> save-file\better-bibtex.sqlite.damaged
> save-file\better-bibtex-search.sqlite

and then remove the BBT extension (verison [test build 6.7.104.2610.4856](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.104.2610.4856.xpi)), and reinstall the version of released [v6.7.103](https://github.com/retorquere/zotero-better-bibtex/releases/download/v6.7.103/zotero-better-bibtex-6.7.103.xpi). There is no problem now, everything still works fine.

5. Now files in `save-file\`, including

> save-file\better-bibtex\ (some `json.bak` file in it)
> save-file\better-bibtex.sqlite
> save-file\better-bibtex-search.sqlite

It seems that the problem is not caused by the extension itself, but due to other reasons like unexpected terminations maybe? My computer's graphics card is broken, so it sometimes become bluescreened and I have to force the computer to restart. I am sure the Zotero is on at that time, so I consider it may be one reason on corrupting the sqlite file. Or do you need the corrupted sqlite file for further analysis?

Hope these information may help you. Thank you for your help again.

**Comment by retorquere** [comment]
> I do not have any idea on how it got corrupted, but here is some information that may help you find the root of the problem:
> 
>     1. I have tried the released version of 6.7.102/103/104 at the beginning, but the problem did not fix. After I installed [test build 6.7.104.2610.4856](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.104.2610.4856.xpi) and upload the debug log, you say that the sqlite file is corrupted. I delete this file after I backup it, and the problem fix.

That sounds about right. BBT is not robust against its database being corrupted. An alternate loading mechanism is planned which may help, but that's not a short-term thing.

>     2. Then I tried to edit the backup file, but failed. The result says that `Error: file is not a database`.

Once that has happened, there's not much you can do. BBT cannot cause this itself BTW, this is Zotero-managed, and that mechanism itself is very robust.

> and then remove the BBT extension (verison [test build 6.7.104.2610.4856](https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-6.7.104.2610.4856.xpi)), and reinstall the version of released [v6.7.103](https://github.com/retorquere/zotero-better-bibtex/releases/download/v6.7.103/zotero-better-bibtex-6.7.103.xpi). There is no problem now, everything still works fine.

Any of those versions would have worked, the database handling hasn't changed in forever.

> It seems that the problem is not caused by the extension itself, but due to other reasons like unexpected terminations maybe? My computer's graphics card is broken, so it sometimes become bluescreened and I have to force the computer to restart. I am sure the Zotero is on at that time, so I consider it may be one reason on corrupting the sqlite file. Or do you need the corrupted sqlite file for further analysis?

I don't think I can tell much from the damaged file to learn about the cause, but I'd be happy to take a look. A blue-screen is a plausible cause -- here's a list of causes that the database engine makers have identified: https://www.sqlite.org/howtocorrupt.html

**Comment by JackFishxxx** [comment]
OK, here is the sqlite link:
https://drive.google.com/file/d/1xGzyyi-KVWmupaqS4Acgbqe9_nanaq0K/view?usp=sharing

**Comment by retorquere** [comment]
That's a screenshot of what appears to be a mobile app.
